export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_CART = 'REMOVE_CART';
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';
export const CHECK_CATEGORY = 'CHECK_CATEGORY';
export const CHECK_UNIT_MONEY = 'CHECK_UNIT_MONEY';
export const UNSELECT_PRODUCT = 'UNSELECT_PRODUCT';
